package com.moblin.android.platform.video

const val kCVImageBufferColorPrimariesKey = "CVImageBufferColorPrimaries"
const val kCVImageBufferYCbCrMatrixKey = "CVImageBufferYCbCrMatrix"
const val kCVImageBufferTransferFunctionKey = "CVImageBufferTransferFunction"
const val kCVImageBufferCGColorSpaceKey = "CVImageBufferCGColorSpace"
const val kCVBufferPropagatedAttachmentsKey = "PropagatedAttachments"
const val kCVImageBufferColorPrimaries_P3_D65 = "P3_D65"
const val kCVImageBufferLogTransferFunctionKey = "LogTransferFunction"
const val kCVImageBufferLogTransferFunction_AppleLog = "AppleLog"
const val kCVImageBufferTransferFunction_ITU_R_2100_HLG = "ITU_R_2100_HLG"
const val kCVImageBufferColorPrimaries_ITU_R_709_2 = "ITU_R_709_2"
const val kCVImageBufferColorPrimaries_ITU_R_2020 = "ITU_R_2020"
const val kCVImageBufferTransferFunction_ITU_R_709_2 = "ITU_R_709_2"
const val kCVImageBufferYCbCrMatrix_ITU_R_601_4 = "ITU_R_601_4"
const val kCVImageBufferYCbCrMatrix_ITU_R_709_2 = "ITU_R_709_2"
const val kCVImageBufferYCbCrMatrix_ITU_R_2020 = "ITU_R_2020"
