package com.moblin.android.various

import com.moblin.android.integrations.workoutdevice.WorkoutDeviceRunningMetrics
import com.moblin.android.various.managers.GForce
import java.time.Instant

data class Variables(
    val timestamp: Long,
    val bitrate: String,
    val bitrateAndTotal: String,
    val bonding: String,
    val resolution: String?,
    val fps: Int?,
    val date: Instant,
    val debugOverlayLines: List<String>,
    val speed: Double,
    val averageSpeed: Double,
    val altitude: Double,
    val distance: Double,
    val splitDistance: Double,
    val altitudeAscent: Double,
    val altitudeDescent: Double,
    val splitAltitudeAscent: Double,
    val splitAltitudeDescent: Double,
    val slope: String,
    val conditions: String?,
    val condition: String?,
    val temperature: Double?,
    val feelsLikeTemperature: Double?,
    val windSpeed: Double?,
    val windGust: Double?,
    val country: String?,
    val countryFlag: String?,
    val state: String?,
    val area: String?,
    val city: String?,
    val neighborhood: String?,
    val muted: Boolean,
    val heartRates: Map<String, Int?>,
    val activeEnergyBurned: Int?,
    val workoutDistance: Int?,
    val power: Int?,
    val stepCount: Int?,
    val teslaBatteryLevel: String,
    val teslaDrive: String,
    val teslaMedia: String,
    val cyclingPower: String,
    val cyclingCadence: String,
    val cyclingSpeed: Double,
    val runningMetrics: Map<String, WorkoutDeviceRunningMetrics>,
    val browserTitle: String,
    val gForce: GForce?,
    val latestSubscriber: String,
    val latestFollower: String,
    val systemMonitor: String
)
