package com.moblin.android.view.settings.about

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.moblin.android.platform.swiftui.NavigationStack
import com.moblin.android.platform.swiftui.NavigationTitle
import com.moblin.android.platform.swiftui.formPalette

data class Version(
    val version: String,
    val date: String,
    val changes: List<String>,
)

private val versions: List<Version> = listOf(
    Version(
        "35.5.0",
        "2026-10-08",
        listOf(
            "• Lots of video color changes.",
            "  • New color range setting in Settings → Streams → My stream → Video → Color range. Full or limited range.",
            "  • Trying to correctly include color metadata in recordings and stream.",
            "  • Full range by default, just as before. Limited is probably the better choice unless you are using a USB camera to iPad.",
            "• YouTube ban and timeout viewers. 💡 G",
            "• Workaround for high CPU usage mediaplaybackd process.",
            "• German translation updated. ✍️ MaurisonX",
            "• Brighter colors for OA4 over USB to iPad when \"Limited color range\" is selected in stream settings and \"External camera video range\" debug setting is enabled.",
            "• Refactoring of how mics and video sources are represented internally.",
            "• Fix many bad translation that were just copies of English.",
            "• Make replays cleanup more efficient. 🧑‍🏭 VazhnovPavel",
            "• Only use even virtual ports in RIST server ingest to make retransmissions work. 🐛 gabbloxen",
            "• Namespace all global definitions in injected javascript code in browser widgets.",
            "• Remove red line from chat.",
            "• Fewer duplicated browser widget frames when showing video.",
            "• Make key bindings work better. 🐛 kharbm-hash",
            "• Browser widget viewport and safe area changes.",
            "• Keep audio running through interruptions such as emergency alerts. 🐛 bwang",
            "  • Will output silence until interruption ends.",
            "• Show video source widgets when camera preview quick button is enabled.",
            "  • Face tracking is only applied on stream.",
            "• Do not show first time chatter in activity feed.",
            "• Notification macro action to show a message in activity feed. 💡 Crozbo",
            "• Chat message filter action to show in activity feed. 💡 slachy",
            "• PiP scene by default.",
            "• Various DJI device protocol/detection improvements. 🧑‍🏭 iChrisIRL",
            "• DJI Pocket 4 Pro support? 🧑‍🏭 iChrisIRL",
            "• HTTP client preparations for optional \"bonding\" proxy.",
            "• Try to make browser widget reload work better.",
            "• Filter for quick button list in settings.",
            "• Optionally say emote names in text to speech. 💡 slachy",
        ),
    ),
    Version(
        "35.3.0",
        "2026-09-25",
        listOf(
            "• Show Twitch anonymous gift subs. 🐛 G",
            "• Try to make background streaming work better when Camera preview quick button is on. 🐛 HeroHarmony",
            "• Remove RTMP drift tracking toggle.",
            "• Total ingests jitter buffer makeover.",
            "• Render emotes in alerts widget.",
            "• Alerts widget positioning with alignment.",
            "• Make hype train banner look better.",
            "• Fix emotes in /me. 🧑‍🏭 gabbloxen",
            "• Fix YouTube login cancelled crash.",
            "• Simplify Twitch login.",
            "• Less risk of logging out wrong Twitch stream.",
            "• Audio refactoring and remove unknown level. 🧑‍🏭 xcopy94",
            "• Kick access token in keychain. 🧑‍🏭 iChrilIRL",
            "• Make it possible to accept Kick \"cookies\" by allowing scrolling.",
            "• Make macro events set variables that following actions can use.",
            "• Fix quick button settings applied to wrong quick button. 🐛 HeroHarmony",
            "• Various changes to video capture setup.",
            "• Remove photo shoot connections and outputs from capture session.",
            "• Experimental native low light boost debug toggle. 🧑‍🏭 SM9();",
            "• Twitch EventSub reconnect when subscribe fails.",
            "• Subscribe to Twitch events in parallel.",
            "• Show sent shoutouts in chat and activity feed.",
            "• Downsample big .png LUTs to fit in texture. 🐛 Crash dump",
            "• LUTs loading optimizations.",
            "• Chat text font picker. 💡 Someone in chat",
            "• Toggle to only allow TTS when a bluetooth speaker is connected. 💡 HeroHarmony",
            "• Macro event variables usability.",
            "• Faster export and import, but slightly larger archives.",
            "• Make test to speech delay between messages work on iOS 27. Apple bug. 🐛 HeroHarmony",
            "• New raid search result sorting.",
            "• Show viewer count in Twitch raid search results.",
            "• Do not show null island in map widget.",
        ),
    ),
    Version(
        "35.2.0",
        "2026-09-18",
        listOf(
            "• Configurable scene buttons colors. 💡 JohannesLiv",
            "• Configurable zoom preset button color.",
            "• Remove settings images when resetting/importing settings.",
            "• Do not allow uploading snapshot as part of go live notification to Moblin website. 💡 Chat",
            "• Make scene and zoom preset buttons look better. 💡 3l3ktr0l4mpe",
            "• Show banner with various info, like poll, prediction, raid, etc. in main view.",
            "  • Tap it to minimize.",
            "• Twitch chatter name color and badges in events.",
            "• Fix possible crash when thermal state changes. 🧑‍🏭 gabbloxen",
            "• Fix browser widget bug making teardown not work. 🧑‍🏭 gabbloxen",
            "• Fix possible MPEG-TS decode crash and encode timestamp wraparound encode bug. 🧑‍🏭 gabbloxen",
            "• Make icon as face blur work better to the left in the image. 🧑‍🏭 gabbloxen",
            "• Fix off by one in LUT calculations. 🧑‍🏭 gabbloxen",
            "• Fix remote control relay toggle. 🧑‍🏭 gabbloxen",
            "• Faster .cube LUT loading.",
            "• Use SRT overhead bandwidth and maximum bandwidth follow input settings. 🧑‍🏭 gabbloxen",
            "• Set the torch quick button state from remote control instead of toggling it. 🧑‍🏭 gabbloxen",
            "• Add the lock screen quick button to the database again. 🧑‍🏭 gabbloxen",
            "• Fix various threading, cast and range problems.",
            "• Wait for event macro action.",
            "• Ignore data from old Moblink, Remote control and OBS remote control connections.",
        ),
    ),
    Version(
        "35.1.0",
        "2026-09-15",
        listOf(
            "• Add BLE cycling speed and cadence (CSC) workout device support. 🧑‍🏭 KleMiX",
            "• Live2D in VTuber. 💡 Aislynn Bloomtear and Spillmaker",
            "• Fix manual Moblink relay streamer URL validation. 🐛 NT4admin®",
            "• Improved chat bot command input validation.",
            "• Optional Go live notification to Moblin website. 💡 JohannesLiv",
            "• Improved input validation in general.",
            "• Move Moblin icon slightly down in face blur effect.",
            "• SRT 1.5.7.",
            "• Try to fix crash the sometimes happens when starting or stopping a stream.",
            "• Lots of Swift 6 adaptions.",
            "• Fix for stream playing in Kick auth. 🧑‍🏭 iChrisIRL",
            "• Various improvements to workouts. 🧑‍🏭 KleMiX",
            "• Make ABR rate control work on iOS 27 by not settings data rate limit.",
            "• Fix quick button safe area when building with Xcode 27.",
            "• Make looping macros not crash when no delay action.",
            "• Create widget effect wizard.",
            "• Show YouTube super sticker and super chat amount when compact events are enabled. 🐛 xcopy94",
        ),
    ),
    Version(
        "35.0.0",
        "2026-09-09",
        listOf(
            "• Show wrong password message in remote control streamer.",
            "• Make changing control bar background image crop less laggy.",
            "• Simplify DjiDevice and GoPro code.",
            "• Fix Twitch events filtering, especially shared chat.",
            "• Simplify SSID selection.",
            "• Show message if location permission is not allowed.",
            "• Make scroll work in whole control bar.",
            "• Align video to control bar when wide.",
            "• Do not allow portrait streaming on Mac for now.",
            "• Initial support for showing Twitch polls and predictions. 💡 Chat",
            "• Remove recordings quick button.",
            "• Various internal changes to events that may break something.",
            "• Auto logout from Twitch if re-login is required.",
            "• Compact events setting. 💡 3l3ktr0l4mpe",
            "  • Compact by default.",
            "• Activity feed separator redesign. 💡 Chat",
            "• Vibe coded full rewrite of chat rendering for better performance.",
            "  • No idea if it works =)",
            "• Peak audio level. 🧑‍🏭 xcopy94",
            "• Hide quick buttons in chat phone mode. 💡 Crozbo and chat",
            "• Moderation actions in main chat in chat phone mode.",
            "• Show suggestions on Twitch raid page.",
            "• HTTP proxy optionally accessible from other devices.",
            "• Initial support for Twitch poll and prediction management.",
        ),
    ),
    Version(
        "34.2138.0",
        "2026-09-06",
        listOf(
            "• !moblin custom <name> to define custom chat bot commands. Define format string with variables, much like for the text widget. 💡 Crozbo",
            "• Make animated chat emotes use less CPU.",
            "• Make chat message border use less CPU.",
            "• Make quick button states work after settings import.",
            "• Use notification event instead of subscription events.",
            "• Send chat message macro action. 💡 Crozbo",
            "• Run macros in remote control assistant. 💡 Crozbo",
            "• Optionally show twitch watch streaks in chat. 💡 Grandin Kartsa and mikeful",
            "• Optionally turn off drift tracking in RTMP server streams for debugging.",
            "  • For Ticans testing.",
            "• Number of chat messages to show setting in chat widget.",
            "• Optionally show selected icon when face blurring. 💡 9philip and Tican",
            "• {bonding} variable. 💡 9philip and others",
            "• Show 1/x as value for exposure and do not use some values. 💡 Murrito",
            "• Make scene quick switch work with camera preview quick button enabled. 💡 xcopy94",
            "• Show device total CPU usage instead of Moblin process CPU usage.",
            "• Toggle to always attach camera preview to capture session.",
            "• Default video source as None instead of Screen capture.",
            "• Toggle to always attach photo shoot to capture session.",
            "• Make twitch announcements show in chat.",
            "• System monitor variable, {systemMonitor}, in debug section.",
            "• Lower CPU usage when enabled bluetooth devices are not nearby.",
            "• Chat phone mode. 💡 xcopy94",
            "• Big Twitch GIFs.",
            "• Gigantified Twitch emotes.",
            "• MacOS status menu icon.",
            "• Recording refactoring.",
            "• Optionally make all chat names same color. 💡 Tican",
            "• GoPro bluetooth. 🧑‍🏭 iChrisIRL",
            "• Activity feed.",
            "• Prefer still images over GIFs when animated emotes settings is off.",
            "• Fuzzy matching chat bot command arguments. 💡 xcopy94",
            "• Select control bar background image.",
            "• Remote control assistant can send text messages to streamer. 💡 3l3ktr0l4mpe",
            "• Optionally show Twitch shared chat events. 💡 Someone in Twitch chat",
        ),
    ),
    Version(
        "34.2137.0",
        "2026-08-30",
        listOf(
            "• Make SRT server ingest work when your device has multiple network interfaces.",
            "• Torch brightness slider. 💡 Kosta X",
            "• Drop old video frames and audio buffers.",
            "• Configurable delay per mic.",
            "  • Settings → Audio → Delays.",
            "• Probably less problems in recordings when having audio disruptions.",
            "• Select mic after importing settings.",
            "• Use gemini-3.5-flash-lite as default chat bot ai ask model.",
            "• Better chat bot ai ask error replies.",
            "• Show toast when Twitch/Kick/YouTube authentication tokens expires.",
            "• Delete unused authentication tokens on app startup.",
            "• Make remote control status icon in top right show correct color.",
            "• Let user know that MetalPetal does not work when Moblin is in background.",
            "• Truncate long Twitch chat messages before sending them. 🐛 Tican",
            "• Correct selected zoom button in web remote control.",
            "• More gimbal controls via remote control.",
            "• SEI timecodes refactoring.",
            "• Mobcam for using Moblin as a webcam in OBS. 💡 Tican",
            "• Italian translation updated. ✍️ Alfa",
            "• Make Mac screen capture colors look better with MetalPetal.",
        ),
    ),
    Version(
        "33.2137.0",
        "2026-08-17",
        listOf(
            "• Hopefully no more audio glitches when switching builtin camera.",
            "• German translation updated. ✍️ MaurisonX",
            "• Leetspeak (1337) translation. 🧑‍🏭 Claude",
            "  • Select Esperanto as app language in iOS settings.",
            "• Make DJI devices work directly after importing settings. 🐛 Claude",
            "• Claude trying to fix the bugs it introduced in \"Fix RTMP sometimes fails to connect.\" fix. 🐛 Claude",
            "• Try implementing \"Fix RTMP sometimes fails to connect.\" properly. 🧑‍🏭 Claude",
        ),
    ),
    Version(
        "33.1337.0",
        "2026-08-14",
        listOf(
            "• Optional chatter name in Open Streaming Platform chat messages. 🧑‍🏭 e22ha",
            "• Only show Apple Music settings when show all settings toggle is enabled.",
            "• Save settings button. 💡 3l3ktr0l4mpe",
            "• Scene video source mirror toggle. 💡 ANDI_CUTBRAY",
            "• Keep a list of saved remote control assistant URLs to make it easier to switch. 💡 Kentar75",
            "• Click/tap control bar and GoPro page indicators to switch page. 💡 ANDI_CUTBRAY",
            "• Make sparkle effect easier to see.",
            "• Core Image or MetalPetal for graphics processing. 🧑‍🏭 💡 hilxen",
            "  • Select in Settings → Scenes → Graphics.",
            "• Chinese (HK) translation updated. ✍️ tkg2222",
            "• Send map course and speed over remote control.",
            "• Import settings via remote control.",
            "  • Assistant sends settings to streamer.",
            "• Make SRT client show ingests status in top right.",
            "• Bump official SRT lib to version 1.5.6.",
            "• Bump RIST lib to version v0.2.20.",
            "• Bump WHIP/WHEP lib to latest master.",
            "• Move high quality downsampling toggle to Graphics page.",
            "• Support for Black Shark Magcool Pro 5. 🧑‍🏭 Spillmaker",
            "• Stats (similar to text widget variables data) from remote control streamer to assistant. 🧑‍🏭 NoFuture",
            "• Make remote control streamer able to connect to localhost.",
            "• Software video decoding toggle in ingests settings.",
            "• Make debug logging setting take effect after import.",
            "• Fix memory leak in SRT server and client ingests. 🧑‍🏭 Claude",
            "• Fix RIST server ingest crash. 🧑‍🏭 Claude",
            "• Make more ingests successfully decode first received video frame. 🧑‍🏭 Claude",
            "• Rename Kick host to raid. 🧑‍🏭 iChrisIRL",
            "• Send reply if requested song via chat bot if not found.",
            "• Fix WHEP client and WHIP server ingests sometimes freeze. 🧑‍🏭 Claude",
            "• Fix RTSP client ingest sometimes having wrong timestamps. 🧑‍🏭 Claude",
            "• Fix RTMP sometimes fails to connect. 🐛 VazhnovPavel",
            "• Fix RTSP client ingest for H.265 from ffmpeg. 🧑‍🏭 Claude",
        ),
    ),
    Version(
        "33.12.0",
        "2026-07-23",
        listOf(
            "• Try to make chat usernames more readable on dark background. 💡 Tican",
            "• Set talkback mic in remote control. Streamer side only.",
            "• Make SRT client ingest work when reconnecting. 🐛 iesv",
            "• Make audio work in SRT client ingest. 🐛 iesv",
            "• Stop SRT clients when entering background when not streaming, otherwise crash when entering foreground. 🐛 iesv",
            "• Stop WHIP server when entering background when not streaming.",
            "• Make image stabilization work when scene video source is not a builtin camera. 🐛 MikeV",
            "• Recording on separate dispatch queue not to block pipeline queue when starting recording.",
            "• Experimental Apple Music control via chat bot and player.",
            "• Altitude ascent and descent in text widget. 🧑‍🏭 NoFuture",
            "• Apply font size setting to quick button chat. 💡 G",
            "• YouTube stream management and viewers tweaks.",
            "  • May slightly reduce number of requests. Almost reached quota limit.",
            "• Photo shoot quick button for taking highish resolution clean pictures periodically. 💡 G",
            "  • One picture per active builtin/UVC camera per second.",
            "  • Pictures saved to Photos (not uploaded to Discord).",
            "• Try to make Moblink reconnection work better. 🐛 AUTdany",
            "• Case-insensitive chat bot commands. 💡 Real Life Doomer",
            "• Chinese Taiwan translation updated. ✍️ 一人HitoriGS —",
        ),
    ),
    Version(
        "33.11.0",
        "2026-07-05",
        listOf(
            "• Only show \"Failed to fetch youtube video ids\" toast when youtube is configured.",
            "• Make talkback work after app has been in background. 🐛 Rick9K",
            "• Better audio handling in MPEG-TS reader. 🐛 Testlin",
            "• Non-blocking official SRT send so app does not hang when pushing lots of data. 🐛 Testlin",
            "• Chinese Taiwan translation updated. ✍️ 一人HitoriGS",
            "• Russian translation updated. ✍️ Murrito",
            "• Do not show frozen first frame when ingest connects.",
            "• Replace copy button with share and/or QR code buttons. 💡 JohannesLiv, codemonkeybb and others",
            "• Scrollable debug log share view. 🐛🧑‍🏭 xcopy94",
            "• Debug toggle to enable/disable SRT(LA) packet padding. 💡🧑‍🏭 grimfoss",
            "  • Disabled by default.",
            "• Keep SRT(LA) URL query parameters entered in create stream wizard. 🐛 grimfoss",
            "• Show weather and location data in text widget in remote scene. 🐛 Someone watching my stream",
            "• Font picker in text widget.",
        ),
    ),
    Version(
        "33.10.0",
        "2026-06-26",
        listOf(
            "• Single line moderator chat messages and less noticeable replies. 💡 Landy's secret streamer",
            "• Do not include moderator messages in alerts chat filter.",
            "• Make stream decks easier to configure.",
            "• Black Stream Deck keys by default. 💡 mikeful",
            "• Show confirmation before ending/deleting a YouTube stream. 💡 cliffcreates",
            "• Chat from multiple YouTube video ids at once. 💡 cliffcreates 🧑‍🏭 ParaisosPeloSul",
            "  • Comma separated list of video ids.",
            "• German translation updated. ✍️ MaurisonX",
            "• Rename setStream to setLive in remote control protocol.",
            "  • Breaking change!!!",
            "• Disable browser bonding by default. 🐛 thomaserlang",
            "  • Also reload the HTTP proxy when entering foreground and when reloading browser widgets.",
            "• Finnish translation updated. ✍️ mikeful",
            "• 25 minutes option in Pomodoro timer. 🧑‍🏭 mikeful",
        ),
    ),
    Version(
        "33.9.0",
        "2026-06-23",
        listOf(
            "• Make DJI device auto start on app start when auto IP address is configured. 🐛 schieder-karl",
            "• More options in auto scene switcher time picker. 💡 PIRATO",
            "• Fix remote scene widget positioning.",
            "• YouTube moderator support. 💡 LunaMach",
            "• Use a Stream Deck to control Moblin on iPad. 💡 Mechanic Eric AMericA",
            "  • Normal keys only.",
            "• Make browser bonding work better. 🐛 Alps On Air | John and mikeful",
            "  • It was sometimes losing some data at the end.",
        ),
    ),
    Version(
        "33.8.0",
        "2026-06-19",
        listOf(
            "• Kick level badges. 🧑‍🏭 iChrisIRL",
            "• Mod action to show/hide Kick channel live view count. 🧑‍🏭 iChrisIRL",
            "• Make DJI device RTMP URL easier to understand???",
            "• Support for OA6 DJI device. 🧑‍🏭 NoFuture and simon_offiziell",
            "• German translation updated. ✍️ MaurisonX",
            "• Enable HTTP proxy by default.",
            "  • To make browser widgets and builtin browser bond iOS network interfaces.",
            "  • Disable in debug settings.",
            "• Chinese Taiwan translation updated. ✍️ 一人HitoriGS —",
            "• Copy Twitch login state to duplicated stream.",
            "• Macro repeat setting. 💡 Chat",
            "  • Off, count or forever.",
            "• Rename interactive chat quick button to scrollable chat. 💡 xcopy94",
            "• DJI device OA6 video codec setting (HEVC or AVC). 🧑‍🏭 NoFuture",
            "• Chat bot command to send a message.",
            "  • Typically define an alias for it, say !tip.",
            "• Do not reset other widgets when changing image widget image. 💡 elmino",
            "• Show pars toggle in golf full scorecard widget settings. 💡 elmino",
            "• Fetch YouTube handle after logging in.",
            "• Disable YouTube fetch video id button if channel handle is empty.",
            "• -1, PAR and +1 score buttons in golf scoreboard remote control. 💡 Saschivus",
            "• Close macros panel on run toggle per macro. 💡 AUTdany",
            "• Track split distance. 🧑‍🏭 NoFuture",
            "  • Can be reset in settings or via chat bot command.",
            "• UTF-8 instead of ASCII in browser widget chat messages. 🧑‍🏭 thecoolrhyno",
            "• Position browser widgets at their configured scene positions in interactive mode. 💡 HappyFluffyTeddy",
            "  • For readable browser widget alerts using front cam when not mirrored to viewers.",
            "• Make it easier to select DJI device WiFi network. 🧑‍🏭 ParaisosPeloSul",
            "• Slightly more efficient browser widget video snapshotting.",
            "• Send speech to text transcript to browser widgets that wants them. 🧑‍🏭 thecoolrhyno",
            "• Reload browser widgets when entering foreground when not streaming.",
            "• Save interactive browsers quick button state persistently.",
            "• Optional distance, altitude, temperature and speed units in text widget. 🧑‍🏭 ParaisosPeloSul",
            "• Add {area} and {neighborhood} text widget variables. 🧑‍🏭 mvanhorn",
            "• Browser widget local only toggle. 💡 Many streamers",
            "• Unique stream and scene names when duplicating.",
            "• Do not interrupt mic when someone is calling.",
            "  • Configure Phone app notification to banner only for this to work.",
            "• Make chat messages from moderators easier to see. 💡 LunaMach",
            "• Make quick button browser background not opaque.",
            "  • Use browser widgets for transparent background.",
            "• YouTube jewels in chat? 💡 LunaMach",
        ),
    ),
    Version(
        "33.7.0",
        "2026-06-01",
        listOf(
            "• Make Pomodoro timer widget phase names configurable. 💡 JohannesLiv",
            "• Add more focus and break icons to Pomodoro timer widget.",
            "• Smaller portrait low fps image.",
            "• Hide/show preview in web remote control. 🧑‍🏭 S1nGeN0r",
            "• Smaller preview in web remote control.",
            "• SRT client ingest (to pull a stream from a server). 💡 9philip",
            "• Add latest subscriber and latest follower text widget variables.",
            "• Load LUTs sequentially.",
            "• Experimental HTTP proxy to make browsers work when bad wifi. 💡 SM9();",
            "  • Enable in debug settings.",
            "• Automatic RTMP URL mode in DJI device. 💡 verena and MoritzSchmid1",
            "  • No need to change RTMP URL when connected to a WiFi router.",
            "• Make DJI device RTMP URL easier to understand.",
            "• Update deep link stream import to merge with existing streams by name. 🧑‍🏭 jkaretsky",
        ),
    ),
    Version(
        "33.6.0",
        "2026-05-25",
        listOf(
            "• Experimental preview live stream. 💡 xcopy94 and others",
            "  • WHIP, 360p H.264 500 kbps video, 64 kbps OPUS audio, by default.",
            "  • Settings → Streams → My stream → Preview stream.",
            "• Reconnect preview stream automatically.",
            "• Start/stop preview stream using remote control.",
            "• Confirm dialogs for live, record and preview stream toggles in web remote control.",
            "• Chinese Taiwan translation updated. ✍️ 一人HitoriGS —",
            "• Edit OBS media source input using OBS remote control. 🧑‍🏭 Ducker",
            "• Support for DJI Pocket 4 in DJI devices. 🧑‍🏭 Ducker",
            "• Support for HEVC in RTMP server using standard RTMP protocol (not eRTMP). 🧑‍🏭 Ducker",
            "• Replace log per live session with always writing logs to file. 💡 extremememes",
            "• New web remote control status section design.",
            "• Open directories in Finder on Mac.",
            "• Video preview in web remote control.",
            "• New logic for keeping track of Moblink relays.",
            "• Pomodoro timer widget.",
            "• Map widget size setting. 💡 ParaglidingLive.com | Marco",
            "• Adjusted golf scoreboard par and score picker ranges. 💡 elmino",
            "• Optionally show golf player colors. 💡 elmino",
            "• Fix HTTP content length value parsing. 🐛 SM9();",
            "• Fix Moblin SRT ACK of all packets. 🐛 SM9();",
            "• Make first MPEG-TS packet 188 bytes. 🐛 SM9();",
            "• More RTSP client input validation. 🐛  SM9();",
            "• Make H.265 work better in RTSP client. 🐛 Stiegi_Power",
            "• Add high quality downsampling experimental debug setting.",
            "  • Makes some widgets look better. Uses more CPU/GPU.",
            "• Scoreboard size setting.",
            "• Make \"Restore purchases\" button sync state with Apple servers.",
            "• New persistent storage.",
            "  • Will you lose your settings again???",
            "• Show live activity again when app is running in background.",
            "• Fix buffered video insertion order. 🐛 Copilot",
            "• Disable drift tracking for Mac screen capture to fix lag? 🐛 Copilot",
            "• Higher Mac screen capture latency.",
            "• Stealth mode in remote control. 🧑‍🏭 datagutt",
            "• Show date in log header.",
            "• Mask widget effect.",
            "• Chat emote combo widget. 💡 9philip",
            "• Fix minor (I think) RTMP server bugs. 🐛 Copilot",
            "• Plus and minus buttons to move points in the mask widget effect.",
        ),
    ),
    Version(
        "33.5.0",
        "2026-05-14",
        listOf(
            "• Major re-implementation of the web remote control frontend.",
            "  • Now using SolidJS.",
            "  • Various UI changes.",
            "• Korean translation updated. ✍️ Winter1l",
            "• Various improvements to the web remote control frontend. 🧑‍🏭 3l3ktr0l4mpe",
            "• Improved Mac screen capture.",
            "• Golf scoreboard design tweaks in frontend.",
            "• Disable widget positioning and size buttons when hitting min/max.",
            "• Widget size slider can go to maximum.",
            "• New gimbal tracking quick button icon.",
            "• Fix moblin in mouth, blur background and blur faces quick button states when using filters.",
            "• German translation updated. ✍️ MaurisonX",
            "• Remove live activity as it makes UserDefaults corrupt when starting the app early in the iOS boot sequence. 🐛 Houses and others",
            "  • Technically speaking, it's kinda an Apple bug... sadge...",
        ),
    ),
    Version(
        "33.4.0",
        "2026-05-03",
        listOf(
            "• Enable adaptive bitrate and use CBR for RTMP by default.",
            "• German translation updated. ✍️ MaurisonX",
            "• Toggle to make audio level meter bigger. 💡 Kosta X",
            "  • Settings → Display → Big audio level meter.",
            "• RTSP client ingest URL examples.",
            "• Remove DLive.",
            "• Easier SRT URL paste in Create stream wizard. 💡 S1nGeN0r",
            "• Make Mac screen capture work better when there is no movement.",
            "• Skip TTS immediately instead of on word boundary. 💡 Murrito",
            "• Configurable chat widget height. 💡 mikeful and R•O•X•Y",
            "  • Not perfect, but better.",
            "• Replay layout settings. 💡 bananasplit",
            "• Chinese (HK) translation updated. ✍️ tkg2222",
            "• Make chat (and more) work after URL import. 🐛 Sylver",
            "• Toggle clock in modular scoreboard. 🧑‍🏭 jeromecornet",
            "• Pan and tilt gimbal with game controller thumb sticks. 💡 JohannesLiv",
            "• Macros. 💡 AUTdany",
            "  • Enable/disable scene buttons, switch scene, delay and more.",
            "• Improve remove background effect to avoid transparent dark details. 🧑‍🏭 Copilot",
            "• Disable periodic bitrate change by default.",
            "• Update gimbal preset by log pressing game controller button. 💡 JohannesLiv",
            "• Make scene and zoom preset button text slightly bigger. 💡 hilxen",
            "• Chinese Taiwan translation updated. ✍️ 一人HitoriGS —",
            "• Some translations updated. Formatting should work better.",
            "• Golf scoreboard. 💡 elmino",
            "• Toggle to enable gimbal tracking. Enabled by default. 💡 JohannesLiv",
            "• Fix pixellate state in remote control.",
            "• Make SRTLA keep alive timestamp parsing robust. 🐛 3l3ktr0l4mpe",
            "• Golf full scorecard scoreboard. 💡 Crozbo",
            "  • Requires a golf scoreboard to work.",
            "• Select scoreboard sport in create widget wizard.",
            "• Try to reload all DJI devices.",
            "• Trigger glasses and sparkle with chat bot command.",
            "• Refactor video presentation on screen.",
            "• Refactoring and fix motion and macro gimbal buttons.",
            "• Show rate control in top left.",
            "• Make DJI device settings easier to understand.",
            "• Macro chat bot command. 💡 Murr1to",
        ),
    ),
    Version(
        "33.3.3",
        "2026-04-23",
        listOf(
            "• Try to fix RIST crash when ending stream. 🐛 Rubaz",
            "• Interactive browser widgets.",
            "  • Mainly to get rid of popups.",
            "• Configurable gimbal presets. 💡 3l3ktr0l4mpe",
            "  • Use a game controller, a selfie stick, a keyboard or the remote control assistant to move to a preset.",
            "• More controls in web remote control.",
            "• Gimbal movement control via game controller.",
            "• Gimbal animate.",
            "• Chinese Taiwan translation updated. ✍️ ИƎØ_ΙΙØZ",
            "• Make zoom presets update correctly in remote control assistant.",
            "• Remote control assistant tweaks.",
            "• Chinese (HK) translation updated. ✍️ tkg2222",
            "• Atomic using new lock primitive.",
            "  • Hopefully you won't notice.",
            "• Adaptive bitrate enabled by default for RIST.",
            "• Bonding enabled by default for RIST.",
            "• Include RIST total bytes uploaded in bitrate/total upload status. 💡 🐛 Rubaz",
            "• Include buffered packets in packets in flight stats in RTMP. Also makes estimated RTT slightly higher.",
            "• Various tweaks in RTMP streaming code.",
            "• Move to gimbal preset with chat bot command.",
            "  • !moblin gimbal preset <name>.",
            "• Make ingests work after switching stream (hard reload for now).",
            "• Bitrate stats in top right for WHIP and WHEP ingests.",
            "• Fix chat bot command typos.",
            "• Simplify YouTube setup in Create stream wizard.",
            "• More relaxed RTMP adaptive bitrate.",
            "• Use libRIST 0.2.13 (with some patches, same as before). 💡 johan1111",
            "• Fix confirm dialog messages.",
            "• Fix cat printer twitch follow. 🐛 Real Life Doomer",
            "• Add CBR (Constant) and VBR (Variable) bitrate rate control, along existing ABR (Average).",
            "• Remove danish and greek languages support.",
            "• Chat filters disabled by default. 💡 3l3ktr0l4mpe",
            "  • For less risk of discarding all chat messages.",
            "• Show transport bitrate in debug overlay for SRT(LA). 🧑‍🏭 xcopy94",
            "• Debug toggle for periodic bitrate change.",
            "• Show ingests in top right when WHIP and/or WHEP is enabled.",
            "• YouTube gift in chat. Not tested at all. 💡 LunaMach",
            "• Show live activity on login screen when running in background.",
            "• UDP mode in RTSP client.",
        ),
    ),
    Version(
        "33.2.0",
        "2026-04-11",
        listOf(
            "• Set preferred audio input sample rate to 48 kHz. 💡 KristofferLislegaard",
            "• Video preview quick button. 💡 JohannesLiv",
            "  • Preview ingested streams and change scene video source to one of them.",
            "• Actually delete temporary files. 🐛 Jeffro1265",
            "  • Cleanup is performed on app restart.",
            "• Make screen capture sharper on Mac. 🐛 xcopy94",
            "• Prohibit importing settings when live or recording.",
            "• German translation updated. ✍️ MaurisonX",
            "• Korean translation updated. ✍️ Winter1l",
            "• Remove number of chat messages and number of FFFFF from stream history.",
            "• Update deleted chat messages quicker.",
            "• Hide deleted messages in quick button chat alerts view.",
            "• YouTube stream configuration confirmation.",
            "  • YouTube needs more improvements.",
            "• Chat refactoring.",
            "• Chinese Taiwan translation updated. ✍️ ИƎØ_ΙΙØZ",
            "• Background streaming setting in moblin://. 💡 Sylver",
            "• Right-click menu to make it easier delete streams/scenes/... on Mac with normal mouse. 💡 xcopy94",
            "• Make replay work when recording resolution is overridden. 🐛 jeromecornet",
            "• Post trigger delay replay setting. 🧑‍🏭 jeromecornet",
            "  • To optionally record less than 5 seconds after pressing Instant replay/Save replay.",
            "• Apple DockKit for gimbal controls. 🧑‍🏭 hilxen",
            "  • Zoom wheel and configurable shutter and flip buttons.",
            "• Chat bot command to set zoom. 🧑‍🏭 S1nGeN0r",
            "• Show scene and zoom preset buttons when video preview is active. 💡 고블린",
        ),
    ),
    Version(
        "33.1.0",
        "2026-04-03",
        listOf(
            "• CRT TV filter quick button.",
            "• Do not show iOS Accessibility button shapes in control bar. 💡 Gohgo",
            "• Help for how to fix audio and video desynchronizing in recordings.",
            "  • In Settings → Recordings → Help.",
            "• Hide location status icon in to right by default.",
            "• More YouTube stream scheduler help and configure button. 💡 rsil426",
            "• Human readable recording file names.",
            "• List and download recordings using the remote control web server. 💡 S1nGeN0r",
            "• No whitespaces in filenames. 🐛  S1nGeN0r",
            "• Rename Privacy quick button to Blur background. 💡 xcopy94 and others",
            "• Inline navigation title bar to make scrolling on Mac work better.",
            "• Make settings button easier to tap on Mac.",
            "• Show toast when enabling Camera preview.",
            "• Talk back. 💡 IvanV1986 and others",
            "  • Play audio from an Ingest in your speakers.",
            "• Experimental debug toggle to set preferred audio sample rate to 48 kHz. 💡 KristofferLislegaard",
            "• Port 8310 by default for WHIP server. 💡 mikeful",
            "• Optionally sync WHIP/WHEP audio and video streams to common time base.",
        ),
    ),
    Version(
        "33.0.0",
        "2026-03-26",
        listOf(
            "• Fix text widget wind unit. 🐛 kat",
            "• Export settings with file extension `.moblinSettings`.",
            "• Import settings from clipboard as well.",
            "  • Can import both old JSON format and new `.moblinSettings` files.",
            "• Show confirmation alert when settings are about to be imported.",
            "• Make live and recording confirmation in remote control assistant work better. 🧑‍🏭 xcopy94",
            "• Port 8888 for WHIP by default. 🐛 Jeffro1265",
            "• Show number of SOOP viewers. 🧑‍🏭 고블린",
            "• German translation updated. ✍️ MaurisonX",
            "• Chinese (HK) translation updated. ✍️ tkg2222",
            "• Another WHIP URL example. 💡 Tony Mah",
            "• Try to make mic initialization work every time on Mac.",
            "• Chinese Taiwan translation updated. ✍️ ИƎØ_ΙΙØZ",
            "• Optionally use an image as background instead of blur or pixellate in privacy quick button. 💡 JohannesLiv",
            "• Make Mac screen capture use the same FPS as the stream. 🧑‍🏭 Copilot",
            "• Fix video effects not being applied to a few frames when deleting a widget. 🐛 Gohgo",
            "• Korean translation updated. ✍️ Winter1l",
        ),
    ),
    Version(
        "32.0.0",
        "2026-03-20",
        listOf(
            "• Setting to disable PiP when streaming in background. 💡 cliffcreates",
            "• Move widgets slightly up not to sometimes show a gap.",
            "• Export/import settings via files instead of clipboard.",
            "  • The exported archive contains widget assets.",
            "• Widget positioning lock button.",
            "  • To easily set identical vertical and horizontal offsets.",
            "• Single window on Mac.",
            "  • Was impossible to close second window.",
            "• Make keyboard work on MacOS. 🐛 JohannesLiv 🧑‍🏭 Copilot",
            "• Make text widget Location toggle work.",
            "• Fix V-Tuber shoulders. 🧑‍🏭 kat",
            "• Enable/disable filters over web remote control.",
            "• VTuber arms angle setting. 💡 kat",
            "• 320 kbps maximum audio bitrate when recording. 💡 kat",
            "  • Typically requires stereo mic.",
            "• Make Twitch login work? 🐛 R•O•X•Y",
        ),
    ),
    Version(
        "31.0.0",
        "2026-03-14",
        listOf(
            "• Korean translation updated. ✍️ Winter1l",
            "• Make it look better on Mac. 💡 JohannesLiv",
            "  • Use \"Mac Catalyst\" instead on \"Designed for iPad\" when building for Mac.",
            "  • Screen capture and front camera (if present) scenes by default on Mac.",
            "• Disable quick button hide/show toggle if button is active. 🐛 marcipan",
            "• Widget alignment buttons.",
            "• Widget positioning button increment based on resolution.",
            "• Make wheel of time text size look good in all resolutions.",
            "• H.265 WHIP ingest.",
            "• New widget layout settings design.",
            "• Optionally keep chat alive in background. 🧑‍🏭 xcopy94",
            "• Pink icon. 💡 Anara",
            "• Optional Twitch shared chat icon. 🧑‍🏭 xcopy94",
            "  • Settings → Chat → Shared chat icons to enable/disable.",
            "• Remove streaming platform chat toggles.",
            "  • Always show streaming platform icon is more than one streaming platform is configured.",
            "• Remove Halloween and Halloween pumpkin icons.",
            "• Free icons last in list.",
            "• Audio gain setting. 💡 kat and others",
            "• Make audio level in top right of UI work any(?) mic. 🧑‍🏭 Copilot",
            "• Kick viewer info in quick button chat. 🧑‍🏭 iChrilIRL",
            "• Input gain setting. 💡 kat",
            "• Do not require an Apple Watch to start a workout.",
            "  • Use Start workout button your iPhone to start a workout session on the phone.",
            "  • Use Start workout button your Apple Watch to start a workout session on the Apple Watch.",
            "• More text widget help.",
            "• Do not freeze builtin  and USB (iPad) cams when in background. 💡 Spillmaker and others",
            "  • Will freeze when phone screen is off.",
            "• German translation updated. ✍️ MaurisonX",
            "• Chinese (HK) translation updated. ✍️ tkg2222",
            "• Quick button positioning from settings and some tweaks.",
            "• Show toast when enabling beauty filters as other widgets won't work. 💡 App review",
            "• Tap URL in quick button chat to open it. 🧑‍🏭 xcopy94",
        ),
    ),
    Version(
        "30.2028.0",
        "2026-02-27",
        listOf(
            "• Rename heart rate device to workout device.",
            "• Make cycling power device part of workout device.",
            "• Running workout device. 🧑‍🏭 kowalski",
            "  • For example running pace, cadence and distance from Garmin watch.",
            "• WHIP streaming. 🧑‍🏭 kn0ax",
            "  • No adaptive bitrate.",
            "• Redesigned stream URL help.",
            "  • Only examples now, not templates.",
            "• German translation updated. ✍️ MaurisonX",
            "• Chinese (HK) translation updated. ✍️ tkg2222",
            "• Experimental WHIP ingest. 🧑‍🏭 Copilot",
            "  • Audio not tested.",
            "• Polish translation updated. ✍️ Oskicz25",
            "• Make Kick chat work for channel names with \"_\" in them. 🧑‍🏭 iChrisIRL",
            "• Optional RIST authentication with username and password.",
            "• 5 ms minimum RTMP and RTSP latency.",
            "• Latency setting in RIST server.",
            " • Was 2 seconds earlier.",
            "• Bump dependencies.",
            "• Lots of internal build system changes.",
            "• Refactoring of timestamp handling in ingests.",
            "• Camera man quick button. 🧑‍🏭 Copilot",
            "• Ingests drift adjustment tweaks.",
            "  • Less sensitive adjustment calculation.",
            "  • One big adjustment instead of many smaller adjustments.",
            "  • Make low latency (< 100 ms roughly) ingests not always make up adjustments.",
            "    • They will never adjust up now, which is also bad.",
            "• Widget top center, bottom center, left center, right center and center alignment options. 💡 Scyc, JasonM and 9philip",
            "• Modular scoreboard tweaks. 🧑‍🏭 Scyc",
            "• Support PNGTuber models with blink and mouth in same sprite. 🐛 kat",
            "• YouTube login.",
            "• Make step count in text widget work. 💡 Eddilaxx",
            "  • When a walking or running workout is active.",
            "• Chinese Taiwan translation updated. ✍️ ИƎØ_ΙΙØZ",
            "• Mouth and eyes sensitivity settings in PNGTuber and VTuber. 💡 kat",
            "• Enable/disable various filters with remote control assistant. 💡 DieKutscher",
            "• Adaptive resolution threshold setting. 💡 BottasWMR and others",
            "• Better support for multiple Moblin SRT streams to save SRT server. 🧑‍🏭 jtrk74",
        ),
    ),
    Version(
        "30.2027.0",
        "2026-02-09",
        listOf(
            "• Untested support for Xtra-branded DJI devices. 💡 Mario 🧑‍🏭 Spillmaker",
            "• Toggle for vertically stacked zoom and scene buttons. 💡 Kumamonster",
            "• LUT widget effect. 💡 Dengoso",
            "• Shortcut to scenes from Scene widgets quick button page. 💡 mikeful",
            "• Bingo card widget.",
            "• Move right aligned widgets slightly to the right for less risk of showing background.",
            "• YouTube login and stream scheduling experiment. 💡 Omulus and others.",
            "  • Not generally available. Send me your email if you want to test.",
            "• Experimental support for number of YouTube viewers.",
            "  • You must login for it to work.",
            "• Beauty quick button. 💡 A few people",
            "  • Looks like a magic wand.",
            "  • All widgets and other filters will be disabled when the beauty filter is enabled.",
            "• Chinese (HK) translation updated. ✍️ tkg2222",
            "• German translation updated. ✍️ MaurisonX",
            "• Better looking stream quick button view.",
            "• Chinese Taiwan translation updated. ✍️ ИƎØ_ΙΙØZ",
            "• Scoreboards for more sports. 🧑‍🏭 Scyc",
            "  • Control the new scoreboards using a web browser.",
            "    • Enable the web server in Settings → Remote control → Web.",
            "  • Hockey for example.",
            "• Widget opacity effect. 💡 Deadllee",
            "• Make image widget update when changing image.",
            "• Korean translation updated. ✍️ Winter1l",
            "• Experimental text blur quick button.",
            "  • Will not blur small text as it can be very CPU intensive.",
            "• Make cycling text widget variables part of workout section.",
            "• Generic and padel scoreboards control in scene widgets quick button.",
            "• Quick button page in deep links. 💡 SpaceG33k",
            "• Try to fix number of YouTube viewers when 0.",
            "• Smaller GoPro QR codes.",
            "• Mode picker in Browser widget with Audio only option. 💡 Deadllee 🧑‍🏭 Copilot",
            "• Chat connection status per streaming platform in top left. 🧑‍🏭 Copilot",
            "• Fix deep link creator crash. 🐛 SpaceG33k",
        ),
    ),
    Version(
        "30.2026.0",
        "2026-01-03",
        listOf(
            "• Star and glasses effects in correct position when using other effects at the same time.",
            "• Chinese (HK) translation updated. ✍️ tkg2222",
            "• Keyboard keys must be one letter. 👏 mikeful and xcopy94",
            "• Text widget refactoring.",
            "  • You will hopefully not see any difference.",
            "• Make Twitch live status less likely to show offline after going live.",
            "• SRT implementation picker. Moblin implementation by default. 👏 mikeful and xcopy94",
            "  • Replaces \"New SRT\" debug setting.",
            "• German translation updated. ✍️ MaurisonX",
            "• Remove old remote control audio level from protocol.",
            "• Make OBS remote control status in top left update when toggling OBS remote control on/off.",
            "• Make selfie stick button offer more functions. 🧑‍🏭 xcopy94",
            "• Only allow the streamer to execute stream and scene chat bot commands by default. 💡 Naginreed",
            "• Replace \"Face\" quick button with \"Blur faces\", \"Privacy\" and \"Moblin in mouth\" quick buttons.",
            "• Rename Cosmetics to Store and change its design slightly. 👏 xcopy94, Martisz, mikeful and JohannesLiv",
            "• Chinese Taiwan translation updated. ✍️ ИƎØ_ΙΙØZ",
            "• Remote control assistant websites links.",
            "• Show star and glasses quick buttons as active when tapped. 💡 tkg2222",
            "• Fancy Moblin in mouth quick button icon. 👏 JohannesLiv, xcopy94 and iChrisIRL",
            "• Rename star quick button to sparkle and improve icon. 👏 JohannesLiv, xcopy94 and iChrisIRL",
            "• Always start app with Blur faces, Privacy and Moblin in mouth quick buttons off.",
            "• Slightly less blur by default.",
            "• Persistently store log filter and add reload button.",
            "• Fewer quick buttons on page 1. 💡 9philip",
            "• Arrows to move quick buttons.",
            "• Group quick buttons per page in settings. 💡 xcopy94 and iChrisIRL",
            "• Add Kick login to stream wizard, matching Twitch pattern. 🧑‍🏭 iChrisIRL",
            "• Always show Background streaming toggle.",
            "  • Not only when \"Show all settings\" is on.",
            "• Background streaming toggle in create stream wizard. 🧑‍🏭 xcopy94 and iChrisIRL",
            "• Remove emotes from create stream wizard. 🧑‍🏭 xcopy94 and iChrisIRL",
            "• Current quick button page indicator in landscape mode. 💡 JoliRancher",
            "• Make background streaming blurred frame have correct size. 🐛 Murrito",
            "• Show Twitch raid progress in quick button chat. 🧑‍🏭 iChrisIRL, xcopy94 and more",
            "• Twitch raid and Kick host channel search. 💡 iChrisIRL 👏 715209",
            "• Allow empty OBS remote control password to make it easier to connect to OBS when authentication is disabled. 💡 Jacxk",
            "• Fix snapshot upload sometimes crash the app.",
            "• Web based remote control started. 💡🧑‍🏭 Scyc",
            "  • The server is running in Moblin.",
            "  • Settings → Remote control → Web.",
            "• Make OBS scene switcher only switch scene when current scene is configured Main or BRB scene. 💡 lewe",
            "• Try to make the OBS scene switcher work better when streaming directly to OBS.",
            "  • Enable Settings → Streams → My stream → OBS remote control → Streaming directly to OBS if you stream directly to OBS.",
            "• Fix chat filter message starts with matching.",
            "  • It only matched beginning of each word, not the beginning of the message.",
            "• Fix text widget timers control.",
            "• Wheel of luck widget.",
            "• Do not trigger delete action on long left swipe on stream, scene or widget. 💡 mikeful",
            "  • Remove delete confirm as long swipe kinda serves this purpose now.",
            "• Stop replay function in controllers. 💡 JasonM",
            "• Korean translation updated. ✍️ Winter1l",
            "• Chat bot commands to enable and disable widgets.",
            "• Chat bot commands to set wheel of luck options and spin it.",
            "• Feels like temperature and wind in test widget. 💡 TimurFearless",
        ),
    ),
    Version(
        "30.2.0",
        "2025-12-27",
        listOf(
            "• Interface name instead of index in Moblink ethernet relay id. 🐛 Djandrea",
            "  • Should make Ethernet relay ids more stable.",
            "• Moderation and predefined messages in new chat menu. 💡 iChrisIRL 🧑‍🏭 iChrisIRL 👏 xcopy94",
            "• Predefined messages quick button.",
            "• New design of \"Send messages to\" selector.",
            "• Make .png LUT loading more robust. 🐛 mikeful",
            "• Face blur and pixellate strength sliders. 💡 BoostedBen",
            "• Blur faces quick button. 💡 Bittersweet1987",
            "  • Can be toggled using keyboard and game controller.",
            "• Privacy quick button. 💡 BoostedBen",
            "  • Can be toggled using keyboard and game controller.",
            "• External link button style consistency.",
            "• Animate copy buttons and remove copy toasts.",
            "• Github icon in help and support.",
            "• Adaptive bitrate refactoring.",
            "• Make adaptive bitrate algorithms start at target bitrate. 💡 xcopy94",
            "• Make it possible to see stream URL when live. 💡 JohannesLiv",
            "• Remote control reliable chat and events redesign.",
            "  • Only for Twitch.",
            "• Move OBS remote control shortcut to bottom of remote control page.",
            "• Optionally show status in top right in stealth mode. 💡 AUTdany",
            "• Fix stealth mode buttons. 🐛 AUTdany",
            "• Recording resolution override help/warning.",
            "• Allow short remote control passwords. 💡 Let me know",
            "• German translation updated. ✍️ MaurisonX",
            "• Chinese (HK) translation updated. ✍️ tkg2222",
            "• Remote control assistant refactoring.",
            "• Button to delete selected replay. 💡 AndreyEng",
            "• Make alerts widget only request face detections when playing.",
            "• Star and glasses effects quick buttons.",
        ),
    ),
    Version(
        "30.1.0",
        "2025-12-20",
        listOf(
            "• Korean translation updated. ✍️ Winter1l",
            "• New speaker keep alive logic.",
            "  • Based on when audio was last played, not periodic.",
            "• Chinese (HK) translation updated. ✍️ tkg2222",
            "• More recordings conversion help.",
            "• Slideshow widget. 💡 mikeful and ROD",
            "  • Can show a text or image widget per slide for configured time.",
            "• Add center alignment option to text widget. 💡 ROD",
            "• Text widget width and corner radius settings. 💡 Stream chat dec 18th",
            "• Polish translation updated. ✍️ kowalski",
            "• Chat and channel moderation. 🧑‍🏭 iChrisIRL",
            "• Scoreboard positioning. 💡 Scyc",
            "• Remove remove wind noise feature.",
            "  • Seems not to work.",
            "• Help the user understand why built-in and USB cameras does not work in background. 💡 xcopy94",
            "• Delete confirmation for streams, scenes and widgets. 💡 FOJD",
            "• Updated websocket 3rd party library.",
            "  • Will chat, remote control and more still work?",
            "• Replace Ads quick button with Moderation quick button.",
            "• Various button changes.",
            "• RTMP compatibility with SRS (bug in SRS imo). 🐛 bani",
            "• Make Moblink relay reuse same id for cellular connection. 🐛 Djandrea",
        ),
    ),
    Version(
        "30.0.0",
        "2025-12-15",
        listOf(
            "• Add \"Remove wind noise\" toggle. 💡 OhItsLaz",
            "  • No idea if it works.",
            "  • Settings → Audio → Remove wind noise.",
            "• Instant scene switching when both scenes uses same cameras. 💡 JohannesLiv",
            "• Quick switch group setting per scene for instant scene switch. 💡 xcopy94 and chat",
            "  • This means high power usage since multiple cameras are capturing video.",
            "• Add 936p 16:9 stream resolution. 🧑‍🏭 Dustinhoefer",
            "  • Camera downscaled from 1080p, means more power usage and possibly worse quality.",
            "• Show toast if replay is enabled but seems unused. 💡 mikeful and xcopy94",
            "• Replace browser widget \"Audio only\" setting with \"Audio and video only\" setting.",
            "  • As video that is paused is not using a lot of power anymore.",
            "• Make browser widget FPS match requested FPS better.",
            "  • Was a bit low earlier.",
            "• Button to toggle small/big web browser. 💡 mikeful and others 🧑‍🏭  mikeful",
            "  • The browser is not visible on stream.",
            "• Allow inline media playback in web browser.",
            "• Streaming platform live status in viewers status in top left. 💡 Anonymous",
            "• Chinese Taiwan translation updated. ✍️ ИƎØ_ΙΙØZ",
            "• German translation updated. ✍️ MaurisonX",
        ),
    ),
    Version(
        "27.7.0",
        "2025-12-08",
        listOf(
            "• Replay stinger help.",
            "• Send low battery chat message when DJI cam is low on battery. 💡 Slaiter",
            "  • Enable with Settings → Chat → Bot → Send low battery message.",
            "• Send low battery chat message every 30 seconds again (not 90 seconds).",
            "• Make DJI device communication not crash on long URL.",
            "• More RTMP streaming from Moblin changes.",
            "• Text widget time and date examples.",
            "• Big muted icon on screen when muted. 💡 Raaaaaad",
            "• Button to reset/clear selected text to speech voice. 💡 Real Life Doomer",
            "• Default language picker for text to speech. 💡 Real Life Doomer",
            "  • To override using app language.",
            "• Reposition alerts widget slightly.",
            "• Support for mp4/mov in alerts widget. 💡 JohannesLiv and others",
            "  • It will not be resized.",
            "  • Audio and video might be slightly out of sync.",
            "• An attempt to make video alerts in browser widget work better. 💡 Pretty much everyone",
            "  • Play inline instead of full screen.",
            "  • Draw video on a canvas to see it on stream.",
            "  • ~30 FPS when video is playing.",
            "• Start a Twitch raid using chat bot command. 💡 Maschu",
            "  • `!moblin twitch raid <channel>`",
            "  • First iteration. To be improved.",
            "  • You must re-login to Twitch for it to work.",
            "• Toggle filters and take snapshots using a game controller and keyboard. 💡 Maschu",
            "• Show toast on Twitch API authentication failure.",
            "• Chinese Taiwan translation updated. ✍️ ИƎØ_ΙΙØZ",
        ),
    ),
    Version(
        "27.6.0",
        "2025-11-29",
        listOf(
            "• Finnish translation updated. ✍️ mikeful",
            "• Do not show low battery warning when using iPhone simulator in Xcode. 🧑‍🏭 xcopy94",
            "• Convert recordings to standard MP4 how-to.",
            "• Korean translation updated. ✍️ Winter1l",
            "• Chinese Taiwan translation updated. ✍️ ИƎØ_ΙΙØZ",
            "• Update battery level in background when Moblink relay is used. 🐛 Djandrea",
            "• Try to end RTMP streams cleanly. 🐛 xcopy94",
            "• Remember stopwatch state when restarting the app. 💡 mikeful",
            "• Set stopwatch time. 💡 mikeful",
            "• Fix RTMP streaming to YouTube, and maybe other platforms. 🐛 Aisu and Maheshh",
        ),
    ),
    Version(
        "27.5.0",
        "2025-11-24",
        listOf(
            "• Show stopwatch when added to text widget. 🐛 mikeful",
            "• German translation updated. ✍️ MaurisonX",
            "• Korean translation updated. ✍️ Winter1l",
            "• Visual effect when tapping various buttons.",
            "  • To make it easier to understand you pressed it.",
            "• 70 ms buffering of builtin audio and video by default.",
            "  • For less dropped frames when using multi cam.",
            "  • You can set it to 0 if you are not using multi cam.",
            "• Resolution setting for recordings. 💡 Scyc and others.",
            "• Rename text widget format specifiers to variables. 💡 cliffcreates",
            "• Text widget suggestions in create widget wizard.",
            "• Show icons next to replay, recording and snapshot settings.",
            "  • To make it easier to associate them with other places in the UI.",
            "• Remove scale to fit width browser widget setting.",
            "• Make browser maximum size by default.",
            "• Show alerts and snapshot widget in configured order.",
            "• Zoom presets in remote control assistant. 💡 Djandera",
            "• Lots of smaller changes to outgoing RTMP, screen capture, recording and more, 💡 xcopy94",
            "• OA6 support in DJI devices (to start stream)? 🧑‍🏭 Spillmaker",
            "• Untested high quality bluetooth mic. Doubt it works.",
            "• Stop RTMP streams with more than 100 MB of data buffered. 🐛 Andee/Rainy",
            "  • Typically happens when the encoder outputs higher bitrate than the network can handle.",
            "• Fix app freezing when chat bottom is ~200px and opening the keyboard.",
            "• Chat widget, showing your chat on stream. 💡 cliffcreates",
            "• Make RTMP server more robust. 🧑‍🏭 iChrisIRL and NoFuture",
            "  • Might fix OA6 audio.",
            "• Show \"No key set\" in keyboard key setting when no key is set.",
        ),
    ),
    Version(
        "27.4.0",
        "2025-11-12",
        listOf(
            "• Snapshot upload robustness experiment. 💡 Djandrea",
            "  • Try cellular, wifi and one ethernet interface.",
            "• Show CPU and RAM usage in top right, not only CPU.",
            "  • RAM usage is interesting when buffering a lot of video.",
            "• H.264/AVC profile setting (Baseline, Main and High). 💡 zeleznypa",
            "• Show Moblink relay id and add a reset button. 💡 JohannesLiv",
            "• Fix Kick login. 🐛 Markus Palmer",
        ),
    ),
    Version(
        "27.3.0",
        "2025-11-10",
        listOf(
            "• Happy icon in shop. 🧑‍🏭 JohannesLiv",
        ),
    ),
    Version(
        "27.2.0",
        "2025-11-02",
        listOf(
            "• Optional AI responses in alerts widget.",
            "  • For example, text to speech of \"erik just followed. <AI rant>\".",
            "• Optionally use TTS.Monster for chat text to speech. 💡 Maz",
            "• Show real FPS in top left. 💡 BoostedBen",
            "  • Updates every 2 seconds.",
            "• Remove MetalPetal (and its beauty filter).",
            "  • Was not maintained.",
            "• Basic navigation by showing a map with walking directions. 💡 Naginreed",
            "  • Open/close with Navigation quick button.",
            "  • Long press to set destination or search for destination.",
            "• Added Chinese Traditional (Taiwan). 💡 ИƎØ_ΙΙØZ",
            "• Encoder resolution in top left Stream status. 💡 NoIP",
            "• Fix chat text to speech sometimes saying the message way too late. 🐛 Melkepakken",
            "• German translation updated. ✍️ MaurisonX",
            "• Chinese simplified translation updated. ✍️ iNove_i9",
            "• Resolution and fps in text widget. 💡 NoIP",
            "• Chinese Taiwan translation updated. ✍️ ИƎØ_ΙΙØZ",
            "• Korean translation updated. ✍️ 위인터",
            "• Generic scoreboard widget. 💡 MRHide",
            "• Configurable scoreboard colors.",
            "• Never delete recordings. 💡 Jordinho_reidelas",
            "  • Do it yourself using the Files app.",
            "• Create widget wizard. 💡 mikeful",
            "  • Select scene(s) to add it to in the wizard. Current scene by default.",
            "• Show version history in bigger window.",
            "• Print twitch redeem rewards with cat printer. 🐛 DrPlankton",
            "• VTuber and PNGTube in bottom right by default.",
            "• Stream in 4:3 aspect ratio. 💡 kyrzixoシ",
            "• Stingers replay transition type.",
            "  • Use your videos as in and out stingers.",
        ),
    ),
    Version(
        "27.1.0",
        "2025-10-22",
        listOf(
            "• Sensitive text as • instead of *.",
            "• Stream URL page redesign.",
            "• Anamorphic lens video effect. 💡 CashMeow, mikeful and others",
            "  • Stream is still 16:9 (with black bars).",
            "• Chat bot commands to start and stop stream. 💡 Deadllee",
            "• Some quick buttons on third page by default.",
            "• Korean translation updated. ✍️ 위인터",
            "• Print subs, follows, etc, with cat printer. 🧑‍🏭 iChrisIRL",
            "• Fix set/get Kick stream title in non-active stream.",
            "• Better start/stop recording confirm text.",
            "• Select a usable builtin video source if the selected builtin video source does not exist. 💡 dhudbjgfvjfc",
            "  • Can happen if moving settings from one phone to another.",
            "• Set Twitch and Kick stream category. 🧑‍🏭 iChrisIRL",
            "• Remove twitch channel id help.",
            "• Remove start/stop recording toasts.",
            "• Quick button to set stream title and category.",
            "• Show channel name in a few places.",
            "• Twitch chat refactoring.",
            "• Shortcut to emotes in chat settings.",
            "• Only show connection priorities settings when SRTLA is configured.",
            "• Hide stream shortcuts if no stream exists.",
            "• Make camera settings buttons shrink if they do not fit.",
            "• Control exposure with camera quick button. 💡 xiaochaosy-code",
        ),
    ),
    Version(
        "27.0.0",
        "2025-10-14",
        listOf(
            "• Fix video source widget rotation. 🐛 Zyiroh and SilleryBay",
            "• Fix replay portrait UI.",
            "• Make alignment take effect immediately in text widget.",
            "• Crop in shape effect.",
            "• Choose SRTLA connection used to register the group by probing RTT. 🧑‍🏭 rationalirl",
            "• RTMP URL handling that may fix Bilibili? 🐛 iNove_i9",
            "• Log video encoder format.",
            "• Make subtitles easier to use.",
            "  • Show available languages.",
            "• Show log full screen. 💡 mikeful",
            "• German translation updated. ✍️ MaurisonX",
            "• Subpages in text widget settings for easier navigation.",
            "• Always show video codec in settings. 💡 mikeful",
            "• Show \"No streamer selected.\" in remote control assistant when none is selected.",
            "• Move \"Video blackish\" to Settings → Scenes.",
            "• Remove experimental Global tone mapping toggle.",
            "• Remove experimental Remove wind noise toggle.",
            "• Remove Reload browser widgets from Scenes settings page.",
            "  • Use quick button instead.",
            "• Minor Scenes settings restructure.",
            "• Show how-to message when selecting screen capture as video source.",
            "• Unique list of network interfaces (bug in iOS 26?).",
            "  • No RTMP/SRT/RIST URL duplicates anymore.",
            "  • Possibly affects other parts of the app that uses networking as well.",
            "• Show OBS logo in a few places. 💡 Martisz 🧑‍🏭 iChrisIRL",
            "• Remove HTTP proxy.",
            "• Remove crop from video source widget.",
            "  • Use shape effect instead.",
            "• Validate ports so app does not crash on bad ports.",
            "• Ultra wide front camera by default if exists.",
            "  • 17 and Air.",
            "• Show fewer settings in basic mode.",
        ),
    ),
)

@Composable
fun AboutVersionHistorySettingsView() {
    NavigationStack {
        NavigationTitle("Version history")
        LazyColumn(
            modifier = Modifier.fillMaxSize(),
            contentPadding = PaddingValues(16.dp),
        ) {
            items(versions, key = { it.version }) { version ->
                Column(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalAlignment = Alignment.Start,
                ) {
                    Text(
                        text = "${version.version} - ${version.date}",
                        fontSize = 22.sp,
                        color = formPalette().label,
                        modifier = Modifier.padding(16.dp),
                    )
                    Column(
                        modifier = Modifier.fillMaxWidth(),
                        verticalArrangement = Arrangement.spacedBy(8.dp),
                        horizontalAlignment = Alignment.Start,
                    ) {
                        version.changes.forEach { change ->
                            Text(
                                text = change,
                                fontSize = 17.sp,
                                color = formPalette().label,
                            )
                        }
                    }
                }
            }
        }
    }
}
